global:
  smtp_smarthost: 'smtp.gmail.com:587'
  smtp_from: 'your email@gmail.com'
  smtp_auth_username: 'your email@gmail.com'
  smtp_auth_password: '{{ env "SMTP_AUTH_PASSWORD" }}'  # Use environment variable for password

route:
  group_by: ['alertname']
  receiver: 'email-alerts'

receivers:
  - name: 'email-alerts'
    email_configs:
      - to: 'recipient-email@example.com'
