auth_enabled: false

server:
  http_listen_port: 3100  # Loki API for Promtail and Grafana
  grpc_listen_port: 9095  # Enable gRPC for advanced use cases (optional)

ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory  # Use 'inmemory' for small setups; use 'memberlist' for larger setups
      replication_factor: 1
    final_sleep: 0s
  chunk_idle_period: 5m
  max_chunk_age: 1h
  chunk_target_size: 1536000
  chunk_retain_period: 30s

schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/boltdb-cache
    shared_store: filesystem
  filesystem:
    directory: /loki/chunks  # Chunks stored here

limits_config:
  enforce_metric_name: false
  reject_old_samples: true
  reject_old_samples_max_age: 168h  # Reject logs older than 7 days (168h)

chunk_store_config:
  max_look_back_period: 0s

table_manager:
  retention_deletes_enabled: true  # Enable retention
  retention_period: 168h  # Retain logs for 7 days
