server:
  http_listen_port: 9080  # Port for Promtail's HTTP server for metrics and health checks
  grpc_listen_port: 0  # Disables gRPC, only HTTP for this instance

positions:
  filename: /tmp/positions.yaml  # Tracks where Promtail last read logs

clients:
  - url: http://loki:3100/loki/api/v1/push  # Push logs to Loki via its API

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*.log  # System logs (adjust if needed)

  - job_name: docker
    static_configs:
      - targets:
          - localhost
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log  # Docker container logs (use JSON format)
