global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'backend_and_frontend_metrics'
    static_configs:
      - targets: ['mern-backend:5001']  # Backend API metrics

  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']   # Monitor Prometheus itself

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # System-level metrics (CPU, memory, disk, etc.)

  - job_name: 'mongodb_exporter'
    static_configs:
      - targets: ['mongodb-exporter:9216']  # MongoDB performance metrics

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']  # Docker container metrics
