 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-database
  namespace: student-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-database
  template:
    metadata:
      labels:
        app: my-database
    spec:
      containers:
        - name: my-database
          image: postgres:alpine
          env:
            - name: POSTGRES_USER
              value: "user"
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: app-secret
                  key: DB_PASSWORD
            - name: POSTGRES_DB
              value: "mydb"
          ports:
            - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  name: my-database
  namespace: student-api
spec:
  type: ClusterIP
  ports:
    - port: 5432
  selector:
    app: my-database
