version: '3'
services:
  api1:
    image: harjotmakkar/backend:latest
    container_name: api1
    ports:
      - "5001:5001"
    networks:
      - my-network
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb

  api2:
    image: harjotmakkar/backend:latest
    container_name: api2
    ports:
      - "5002:5001"
    networks:
      - my-network
    environment:
      - DATABASE_URL=postgres://user:password@db:5432/mydb

  db:
    image: postgres:alpine
    networks:
      - my-network
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=mydb

  nginx:
    image: nginx
    container_name: nginx
    ports:
      - "80:80"
    networks:
      - my-network
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf

networks:
  my-network:
    driver: bridge
